# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_interp <- function(m, fits, slopes, at) {
    .Call('stlplus_c_interp', PACKAGE = 'stlplus', m, fits, slopes, at)
}

c_loess <- function(xx, yy, degree, span, ww, m, l_idx, max_dist) {
    .Call('stlplus_c_loess', PACKAGE = 'stlplus', xx, yy, degree, span, ww, m, l_idx, max_dist)
}

c_ma <- function(x, n_p) {
    .Call('stlplus_c_ma', PACKAGE = 'stlplus', x, n_p)
}

